version: '3.8'

services:
  # Jenkins 서버 (Docker 설치됨)
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=--httpPort=8080
    networks:
      - jenkins-network
    user: root

  # 서버 1 (개발 서버 1)
  server1:
    image: spring-hello:latest
    container_name: server1
    ports:
      - "8082:8080"
    environment:
      - SERVER_NAME=server1
    networks:
      - jenkins-network
    restart: unless-stopped

  # 서버 2 (개발 서버 2)
  server2:
    image: spring-hello:latest
    container_name: server2
    ports:
      - "8083:8080"
    environment:
      - SERVER_NAME=server2
    networks:
      - jenkins-network
    restart: unless-stopped

volumes:
  jenkins_home:

networks:
  jenkins-network:
    external: true